stura_voting/stura_voting/urls.py
# Copyright 2018 - 2019 Fabian Wenzelmann
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""stura_voting URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""

from django.contrib import admin
from django.urls import path, include

from votings.views import profile

urlpatterns = [
    path('votings/', include('votings.urls'), name='index'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/profile/', profile, name='votings_profile'),
    path('admin/', admin.site.urls),
]

stura_voting/votings/urls.py
# Copyright 2018 - 2019 Fabian Wenzelmann
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from django.urls import path

from . import views

urlpatterns = [
    # TODO singular / plural?
    path('', views.index, name='index'),
    path('copyright/', views.copyright_view, name='copyright'),
    path('revision/new/', views.new_revision, name='new_revision'),
    path(
        'revision/<int:pk>/success/',
        views.revision_success,
        name='new_revision_success'),
    path(
        'revision/<int:pk>/edit/',
        views.update_revision_view,
        name='revision_update'),
    path(
        'revision/<int:pk>/delete/',
        views.RevisionDeleteView.as_view(),
        name='revision_delete'),
    path('revision/delete/success/',
         views.revision_delete_success_view,
         name='revision_delete_success'),
    path(
        'revision/<int:pk>/',
        views.RevisionDetailView.as_view(),
        name='revision_detail'),
    path('archive', views.archive_index, name='archive_index'),
    path(
        'period/<int:pk>/edit/',
        views.PeriodUpdateView.as_view(),
        name='period_update'),
    path('period/new', views.new_period, name='new_period'),
    path(
        'period/<int:pk>/delete/',
        views.PeriodDeleteView.as_view(),
        name='period_delete'),
    path(
        'period/<int:pk>/',
        views.PeriodDetailView.as_view(),
        name='period_detail'),
    path('period/delete/success/',
         views.period_delete_success_view,
         name='period_delete_success'),
    path('periods/', views.PeriodsList.as_view(), name='periods_list'),
    path('period/<int:pk>/success/',
         views.PeriodDetailSuccess.as_view(),
         name='period_detail_success'),
    path('sessions/', views.SessionsList.as_view(), name='collections_list'),
    path('session/new/', views.new_session, name='new_session'),
    path(
        'session/<int:pk>/edit/',
        views.SessionUpdate.as_view(),
        name='session_update'),
    path(
        'session/<int:pk>/',
        views.SessionDetailView.as_view(),
        name='session_detail'),
    path(
        'session/<int:pk>/success/',
        views.SessionDetailSuccess.as_view(),
        name='new_session_success'),
    path(
        'session/delete/success/',
        views.success_session_delete,
        name='session_delete_success'),
    path(
        'session/<int:pk>/delete/',
        views.SessionDelete.as_view(),
        name='session_delete'),
    path(
        'session/<int:pk>/print/',
        views.SessionPrintView.as_view(),
        name='session_print'),
    path(
        'session/<int:pk>/voters/',
        views.enter_voterlist,
        name='enter_voterslist'),
    # in the enter_voterslist view links to enter_single_voter are not hidden,
    # should be fine
    path('session/<int:pk>/group/create/', views.new_group, name='session_group_create'),
    path(
        'session/<int:coll>/voters/<int:v>/',
        views.enter_single_voter_view,
        name='enter_single_voter'),
    path('group/<int:pk>/edit/', views.edit_group_view, name='group_update'),
    path(
        'group/<int:pk>/delete/',
        views.VotingGroupDeleteView.as_view(),
        name='group_delete'),
    path('group/delete/success/',
         views.group_delete_success_view,
         name='group_delete_success'),
    path(
        'group/<int:pk>/median/create',
        views.MedianVotingCreateView.as_view(),
        name='group_median_create'),
    path(
        'group/<int:pk>/schulze/create',
        views.create_schulze_view,
        name='group_schulze_create'),
    path(
        'median/<int:pk>/delete/',
        views.MedianVotingDeleteView.as_view(),
        name='median_delete'),
    path(
        'median/<int:pk>/edit/',
        views.MedianUpdateView.as_view(),
        name='median_update'),
    path(
        'schulze/<int:pk>/delete/',
        views.SchulzeVotingDeleteView.as_view(),
        name='schulze_delete'),
    path(
        'schulze/<int:pk>/edit/',
        views.SchulzeUpdateView.as_view(),
        name='schulze_update'),
    # TODO no permission stuff yet
    path(
        'votes/votes_list/<int:pk>/',
        views.session_votes_list,
        name='votes_list'),
    path(
        'session/<int:pk>/results/detailed/',
        views.session_results_votes_view,
        name='session_results_detailed'),
    path(
        'session/<int:pk>/results/',
        views.session_results_view,
        name='session_results'),
]

stura_voting/votings/models.py
# Copyright 2018 - 2019 Fabian Wenzelmann
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from django.db import models

from django.utils import timezone
from django.utils.translation import gettext_lazy

from .utils import *

FIFTY_MAJORITY = '50'
TWO_THIRDS_MAJORITY = '2/3'

MAJORiTY_CHOICES = (
    (FIFTY_MAJORITY, gettext_lazy('50%')),
    (TWO_THIRDS_MAJORITY, gettext_lazy('2/3 majority')),
)


class Period(models.Model):
    """A Period is a timespan in which sessions take place.

    A model has a name (for example Summer Term 2018) and a start and end date.

    Attributes:
        name (models.CharField): The name of the period.
        created (models.DateTimeField): The time the database object was created,
            defaults to now.
        start (models.DateField): The time the period begins.
        end (models.DateField): The time the period ends.

    """
    name = models.CharField(
        max_length=150,
        help_text=gettext_lazy('Name of the Period, e.g. "Summer Term 2019"'),
        unique=True,
        default=get_semester_name)
    created = models.DateTimeField(
        help_text=gettext_lazy('Time of creation'),
        default=timezone.now)
    start = models.DateField(
        blank=True,
        null=True,
        help_text=gettext_lazy('Start date of the period'),
        default=get_semester_start)
    end = models.DateField(
        blank=True,
        null=True,
        help_text=gettext_lazy('End date of the period'),
        default=get_semester_end)

    def __str__(self):
        return str(self.name)


class VotersRevision(models.Model):
    """A revision is a collection of different voters.

    It is associated with the period in which it belongs.

    Attributes:
        period (Period): The period to which this revision belongs.
        created (models.DateTimeField): The time the database object was created,
            defaults to now.
        note (models.TextField): An optional note describing for example why this revision was created.

    """
    period = models.ForeignKey(
        'Period',
        on_delete=models.CASCADE,
        help_text=gettext_lazy('Period this revision belongs to'))
    created = models.DateTimeField(
        help_text=gettext_lazy('Time of creation'),
        default=timezone.now)
    note = models.TextField(help_text=gettext_lazy('Optional note'), blank=True)

    def __str__(self):
        created_format = formats.date_format(self.created, 'DATETIME_FORMAT')
        period = str(self.period)
        return 'Revision vom %s für %s' % (created_format, period)


class Voter(models.Model):
    """A voter that exists in a revision.

    A voter belongs in a certain revision and has a name (string) and weight (positive int).

    Attributes:
        revision (VotersRevision): The revision this voter belongs to.
        name (models.CharField): The name of the group or person.
        weight (models.PositiveIntegerField): The weight of the voter, i.e. how many votes the voter actually casts.

    """
    revision = models.ForeignKey(
        'VotersRevision',
        on_delete=models.CASCADE,
        help_text=gettext_lazy('Revision this user is used in'))
    name = models.CharField(max_length=150,
                            help_text=gettext_lazy('Name of the voter / group'))
    weight = models.PositiveIntegerField(
        help_text=gettext_lazy('Weight of the votes, i.e. how many votes the voter actually casts'))

    def __str__(self):
        return str(self.name)

    class Meta:
        unique_together = ('revision', 'name',)


class VotingCollection(models.Model):
    """A collection of different votings, created with a certain revision (identifying the valid voters).

    A collection (or session) is just a collection of different polls / votings.
    It has a name (e.g. "Meeting on April 18, 2019)", a time when the session takes place and an associated revision.

    Attributes:
        name (models.CharField): The name of the session / collection.
        time (models.DateTimeField): The time when the session takes place.
        revision (VotersRevision): The revision identifying the voters for this session.

    """
    name = models.CharField(
        max_length=150,
        help_text=gettext_lazy('Name of the collection (e.g. "Meeting on XXX")'),
        default=get_next_session_name_stura)
    time = models.DateTimeField(help_text=gettext_lazy('Time the session takes place'),
                                default=get_next_session_stura)
    revision = models.ForeignKey(
        'VotersRevision',
        on_delete=models.CASCADE,
        help_text=gettext_lazy('Group of voters for this session'))

    class Meta:
        permissions = (
            ("view_collection_results",
             "Can view results of a collection"),
            ("enter_collection_results",
             "Can enter results for all who are entitled to vote"),
        )


class VotingGroup(models.Model):
    """A group of votings in a session.

    Each session has different groups in which the actual polls exist.

    Such a group could for example be "Financial Polls" or "Elections for the board of directors".

    Attributes:
        name (models.CharField): The name of the group.
        collection (VotingCollection): The collection in which this group exists.
        group_num (models.PositiveIntegerField): A unique number for each group describing the order in which groups
            are sorted in the session.

    """
    name = models.CharField(
        max_length=150,
        help_text=gettext_lazy('Name of the group, for example "Financial Votes"'))
    collection = models.ForeignKey(
        'VotingCollection',
        on_delete=models.CASCADE,
        help_text=gettext_lazy('Collection this group belongs to'))
    group_num = models.PositiveIntegerField(help_text=gettext_lazy('Order of the group in the session'))

    class Meta:
        unique_together = (('name', 'collection',),
                           ('group_num', 'collection'),)


class MedianVoting(models.Model):
    """A median voting, i.e. a voting of integers in which the first one with a majority wins.

    A single median poll. It belongs in a certain group.
    The poll has a name (for example "Money for party") and the value in question.
    The value is stored in "cent" (whatever this means given a specific currency). That is plain integer values.
    They're parsed in the format "21.00" (meaning 2100 cent) or "42,00" (meaning 4200 cents).
    The currency is used only for displaying purposes.
    As the groups are sorted according to an ordering inside a session the polls in a group are sorted accorded to
    a voting num. This field must be unique, also including schulze polls (though this is not checked on a database
    level).

    Attributes:
        name (models.CharField): Name of the poll.
        value (models.PositiveIntegerField): The value of this poll, always meassured in cents.
        majority (models.CharField): The majority required, at the moment 50% or 2/3. Valid choices are in
            MAJORiTY_CHOICES.
        absolute_majority (models.BooleanField): If true all votes should be counted for the majority, not just the
            votes casted. All voters without a vote should be inserted as a vote for 0 cent.
        currency (models.CharField): The currency to display, only used for displaying. E.g. 4200 with currency "€" is
            displayed as "42,00 €".
        group (VotingGroup): The group to which this poll belongs to.
        voting_num (models.PositiveIntegerField): The sorting position inside the group, must be unique for that group.

    """
    name = models.CharField(max_length=150, help_text=gettext_lazy('Name of the poll'))
    value = models.PositiveIntegerField(
        help_text=gettext_lazy('Value for this voting (for example 2000 (cent). Always meassured in cents, pence etc.)'))
    majority = models.CharField(
        max_length=10,
        help_text=gettext_lazy('Required majority for voting'),
        choices=MAJORiTY_CHOICES,
        default=FIFTY_MAJORITY)
    absolute_majority = models.BooleanField(
        help_text=gettext_lazy('Set to true if all voters should be considerd, even those who did not cast a vote. Thes voters will be treated as if they voted for 0€'),
        default=False)
    currency = models.CharField(
        max_length=10,
        blank=True,
        help_text=gettext_lazy('Currency of the vote, for example "$" or "€". For example value=100 and currency=€ means 1,00€.'),
        default='€')
    group = models.ForeignKey(
        'VotingGroup',
        on_delete=models.CASCADE,
        help_text=gettext_lazy('Group this voting belongs to'))
    voting_num = models.PositiveIntegerField(
        help_text=gettext_lazy('Order position inside the group'))


class SchulzeVoting(models.Model):
    """A schulze voting.

    A single schulze poll. It belongs in a certain group.
    The poll has a name (for example "Election of XXX").
    The options are given by SchulzeOption objects referencing this poll.
    As the groups are sorted according to an ordering inside a session the polls in a group are sorted accorded to
    a voting num. This field must be unique, also including median polls (though this is not checked on a database
    level).

    Attributes:
        name (models.CharField): Name of the poll.

stura_voting/votings/templates/votings/period/all_periods.html
{% extends 'votings/base.html' %}

{% comment %}
Copyright 2018 - 2019 Fabian Wenzelmann

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
{% endcomment %}

{% load bootstrap4 %}

{% block content %}
    <h2>Abstimmungsperioden</h2>
    <table class="table">
      <thead>
        <tr>
          <th>Name</th>
          <th>Von</th>
          <th>Bis</th>
        </tr>
      </thead>
      {% for period in periods %}
        <tr>
          <td><a href="{% url 'period_detail' period.id %}">{{ period.name }}</a></td>
          <td>{{ period.start }}</td>
          <td>{{ period.end }}</td>
        </tr>
      {% endfor %}
    </table>
{% endblock %}

stura_voting/votings/templates/votings/period/new_period.html
{% extends 'votings/base.html' %}

{% comment %}
Copyright 2018 - 2019 Fabian Wenzelmann

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
{% endcomment %}

{% load bootstrap4 %}

{% block content %}
    <h2>Neue Abstimmungsperiode Erstellen</h2>

    <form role="form" method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons submit='Speichern' %}{% endbuttons %}
    </form>
{% endblock %}

stura_voting/votings/templates/votings/period/period_confirm_delete.html
{% extends 'votings/base.html' %}

{% comment %}
Copyright 2018 - 2019 Fabian Wenzelmann

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
{% endcomment %}

{% load bootstrap4 %}

{% block content %}
<div class="alert alert-warning" role="alert">
  <h4><i class="fas fa-exclamation-triangle"></i> Hinweis</h4>
  <p>
  Abstimmungsperioden sollten nur im äußersten Notfall gelöscht werden!
  Es werden alle Revisionen aus dieser Periode gelöscht und alle
  damit assoziierten <b>Sitzungen</b>!
  Der einzige Zeitpunkt an dem eine Periode gelöscht werden sollte ist direkt nach dem Erstellen (wenn es noch keine
  Abstimmung gibt).
  </p>
    <p>
    {% if num_revisions %}
      <b>Es werden insgesamt {{ num_revisions }} Revisionen ebenfalls gelöscht.</b>
    {% else %}
      Es wurden keine Revisionen innerhalb der Periode gefunden.
    {% endif %}
    </p>
    <p>
    {% if num_sessions %}
      <b>Es werden insgesamt {{ num_sessions }} Sitzungen ebenfalls gelöscht.</b>
    {% else %}
      Es wurden keine Sitzungen mit dieser Revision gefunden.
    {% endif %}
    </p>
</div>
    <form role="form" method="post">
      {% csrf_token %}
      <div class="form-group"><button class="btn btn-danger" type="submit"><i class="fas fa-trash"></i> Löschen bestätigen</button></div>
    </form>
{% endblock %}

stura_voting/votings/templates/votings/period/period_detail.html
{% extends 'votings/base.html' %}

{% comment %}
Copyright 2018 - 2019 Fabian Wenzelmann

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
{% endcomment %}

{% load bootstrap4 %}

{% block content %}
<h2>{{ period.name }}</h2>

{% if success %}
    <div class="alert alert-success" role="alert">
    <h4>Erfolg</h4>
        Die Abstimmungsperiode "{{ period.name }}" wurde erfolgreich erstellt.
    </div>
{% endif %}

<p>
    {% if perms.votings.change_period %}
      <a href="{% url 'period_update' object.id %}" class="btn btn-primary" role="button"><i class="fas fa-edit fa-lg"></i> Bearbeiten</a>
    {% endif %}

    {% if perms.votings.delete_period %}
      <a href="{% url 'period_delete' object.id %}" class="btn btn-danger" role="button"><i class="fas fa-trash fa-lg"></i> Löschen</a>
    {% endif %}
</p>

<p>Zeitraum von {{ period.start }} bis {{ period.end }}</p>

<div class="row">
    <div class="col-sm-3 col-md-6">
      <h4>Sitzungen</h4>
      <table class="table">
        <thead>
          <tr>
            <th>Name</th>
            <th>Datum</th>
          </tr>
        </thead>
        {% for coll in collections %}
          <tr>
            <td>
              <a href="{% url 'session_detail' coll.id %}">{{ coll.name }}</a>
            </td>
            <td>{{ coll.time }}</td>
          </tr>
        {% endfor %}
      </table>
    </div>
    <div class="col-sm-9 col-md-6">
      <h4>Revisionen</h4>
      <table class="table">
        <thead>
          <tr>
            <th>Revision</th>
          </tr>
        </thead>
        {% for rev in revisions %}
          <tr>
            <td><a href="{% url 'revision_detail' rev.id %}">Revision vom {{ rev.created }}</a></td>
          </tr>
        {% endfor %}
      </table>
    </div>
</div>
{% endblock %}

stura_voting/votings/templates/votings/period/period_success_delete.html
{% extends 'votings/success.html' %}

{% comment %}
Copyright 2018 - 2019 Fabian Wenzelmann

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
{% endcomment %}

{% load bootstrap4 %}

{% block success %}
Die Abstimmungsperiode wurde erfolgreich entfernt.
{% endblock %}

stura_voting/votings/templates/votings/period/update_period.html
{% extends 'votings/base.html' %}

{% comment %}
Copyright 2018 - 2019 Fabian Wenzelmann

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
{% endcomment %}

{% load bootstrap4 %}

{% block content %}
    <h2>Abstimmungsperiode Bearbeiten</h2>
    <form role="form" method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons submit='Speichern' %}{% endbuttons %}
    </form>
{% endblock %}